# Default values for commons.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
replicaCount: 1
deployment:
  name: catalog-enricher-api
  image:
    repository: quay.io/jcarvaja/quarkus-apps-catalog-enricher
    tag: 1.0.1-SNAPSHOT
    pullPolicy: Always
service:
  name: catalog-rest-api
  type: ClusterIP
  externalPort: 8083
  internalPort: 8083
